[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["oct10_1_graphqlsample"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "oct10_1_graphqlsample"
  org = "tharinduwijewardane"
  version = "3.1.2"

