openapi: 3.0.1
info:
  title: Ignore
  version: 3.1.0
servers:
- url: "{server}:{port}/ignore"
  variables:
    server:
      default: http://localhost
    port:
      default: "8090"
paths: {}
components: {}
